version: '3.8'

services:
  mcp-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TWS_HOST=${TWS_HOST:-host.docker.internal}
      - TWS_PORT=${TWS_PORT:-7496}
      - TWS_CLIENT_ID=${TWS_CLIENT_ID:-1}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
